[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps --prefer-offline --no-audit"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Cache headers for better performance
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Check for broken links
[[plugins]]
  package = "netlify-plugin-checklinks"
  
  [plugins.inputs]
  entryPoints = ["*.html"]
  recursive = true
  pretty = true
  skipPatterns = []
  todoPatterns = []
  checkExternal = false
  followSourceMaps = false

# Inline critical CSS for faster rendering
[[plugins]]
  package = "netlify-plugin-inline-critical-css"

  [plugins.inputs]
  # minify = true
  # basedir = "./dist/public"

# Submit sitemap to search engines
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://okkyno.com"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing",
      "yandex"
    ]

# Optimize images for better performance
[[plugins]]
  package = "netlify-plugin-image-optim"

# Prefetch initial links to improve perceived load time
[[plugins]]
  package = "netlify-plugin-inline-source"

  [plugins.inputs]
    attribute = "inline"

# Check for accessibility issues
[[plugins]]
  package = "netlify-plugin-a11y"

  [plugins.inputs]
    checkPaths = ['/']

[[plugins]]
  package = "@netlify/plugin-cache"

  [plugins.inputs]
    paths = ["node_modules"]
